version: "3.2"

services:
  api:
    image: engageops/docker-luminary:latest-debug
    environment:
      APP_ENV: testing
      APP_DEBUG: 'true'
      CACHE_DRIVER: array
      QUEUE_DRIVER: array
      SESSION_DRIVER: cookie
      DB_CONNECTION: testing
      XDEBUG_CONFIG: "idekey=luminary remote_host=${LOCAL_IP} remote_enable=1"
    volumes:
      - .:/var/www
    ports:
      - 80:8000
# ------------------------------------------------------
# Data Volumes
# ------------------------------------------------------
volumes:
  luminary_test:
