version: "3.2"

services:
  api:
    image: engageops/docker-luminary:debug
    environment:
      APP_ENV: testing
      APP_DEBUG: 'true'
      CACHE_DRIVER: array
      QUEUE_DRIVER: array
      SESSION_DRIVER: cookie
      DB_CONNECTION: testing
    volumes:
      - .:/var/www
    expose:
      - 80
      - 8000
    ports:
      - 80:8000
    links:
# ------------------------------------------------------
# Data Volumes
# ------------------------------------------------------
volumes:
  luminary_test:
